from __future__ import annotations
import os
import structlog
import yaml

logger = structlog.get_logger()


def load_targets(config_path: str = "config/targets.yaml") -> list[dict]:
    if not os.path.isfile(config_path):
        logger.warning("targets_file_not_found", path=config_path)
        return []
    with open(config_path, "r", encoding="utf-8") as f:
        data = yaml.safe_load(f) or {}
    targets = data.get("targets", [])
    return [t for t in targets if t.get("enabled", True)]


def generate_crontab(targets: list[dict], command_template: str = "docker-compose run --rm cypulse scan {domain}") -> str:
    lines = ["# CyPulse Automated Scan Schedule", "# Generated by cypulse scheduler", ""]
    for target in targets:
        schedule = target.get("schedule", "0 2 * * 0")
        domain = target.get("domain", "")
        if domain:
            cmd = command_template.format(domain=domain)
            lines.append(f"{schedule}  {cmd} >> /var/log/cypulse-cron.log 2>&1")
    return "\n".join(lines)
